
const OpenAI = require("openai");
require("dotenv").config();

const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

/**
 * Generate draft response for a given email object.
 * @param {Object} email - The email object { subject, bodyText }.
 */
async function generateDraftResponse(email) {
  const prompt = `
You are a helpful support assistant.
The user wrote this email:
Subject: ${email.subject}
Body: ${email.bodyText}

Analyze sentiment (positive/negative/neutral) and priority (urgent/not urgent).
Generate a professional, empathetic draft reply.
`;

  try {
    const res = await client.chat.completions.create({
      model: "gpt-4o-mini-2024-07-18",
      messages: [{ role: "user", content: prompt }],
    });

    const draft = res.choices?.[0]?.message?.content?.trim();
    console.log("✅ Draft generated by aiService:", draft);
    return draft || "Sorry, no reply generated.";
  } catch (err) {
    console.error("❌ OpenAI draft error in aiService:", err.message || err);
    if (err.response) {
      console.error("OpenAI status:", err.response.status);
      console.error("OpenAI data:", err.response.data);
    }
    return "Sorry, we could not generate a draft reply (AI error).";
  }
}

module.exports = { generateDraftResponse };
